### ISSUE TITLE
[Software] Texture glitch with transparent ghosts

### ISSUE THREAD

**Issue by DrUm78** [fgsfdsfgs/sm64-port#83]
Software: SM64 decompilation fork: https://github.com/DrUm78/sm64-funkey
Hardware: FunKey S device (armv7 32-bit) with 64MB of RAM

Description:
The ghosts have a texture glitch when they are transparent: their face texture is not displayed (see screenshot 2). That's not happening when they are opaque (see screenshot 3).

Steps to reproduce:
1. Use the attached save or use one where you have the ghosts in the castle ([sm64_save_file.zip](https://github.com/fgsfdsfgs/sm64-port/files/11301724/sm64_save_file.zip))
2. Enter the castle and on the right, take the wood door (see screenshot below):
![IMG_0252](https://user-images.githubusercontent.com/46139740/233794704-9e940227-47be-4367-9f47-720756f22f78.PNG)
3. Go to the right to meet the ghost and notice that it's missing its face texture:
![IMG_0261](https://user-images.githubusercontent.com/46139740/233794551-c9df66b1-4e8e-4a97-8fc6-db61ac288632.PNG)
4. Enter the door at the end of the row and meet the ghosts
5. Notice that their face is properly displayed when they are opaque
![IMG_0251](https://user-images.githubusercontent.com/46139740/233794555-cbcd65d5-a41e-4d3e-843f-2f4768fb184e.PNG)

**Comment by fgsfdsfgs** [comment]
Is this only happening on the funkey fork? If not, it's likely missing a decal-mode shader implementation.

**Comment by DrUm78** [comment]
I cannot test right now on another platform but my FunKey fork is up to date with your dos branch.

**Comment by DrUm78** [comment]
FYI this port uses `(GRUCODE), f3dex2e)` microcode.

**Comment by fgsfdsfgs** [comment]
The soft renderer just has a list of shader IDs in it for which to use decal texturing, defined [here](https://github.com/fgsfdsfgs/sm64-port/blob/dos/src/pc/gfx/gfx_soft.c#L695). It's likely that I either just forgot the shader ID for the translucent Boo face in there or `combine_tex_rgba_decal` is broken.

**Comment by DrUm78** [comment]
Does this shader ID exist so I can try to compile with it?

**Comment by fgsfdsfgs** [comment]
I don't know it. I'll have to log them in `gfx_soft_create_and_load_new_shader` and go to that spot in the game.

**Comment by DrUm78** [comment]
@fgsfdsfgs I confirm that the issue also happens on Windows DOS port in software mode (built from your repo):

![Sans titre](https://user-images.githubusercontent.com/46139740/233863957-cb986233-0f54-41a7-81dd-e11fa7ff3e1f.png)

**Comment by DrUm78** [comment]
I'm not very familiar with code logging but I tried `printf("shader_id=%d\n", shader_id);` before line 688 in gfx_soft.c but all I get is a list of numbers that are not similar to the existing shader_id:
```
shader_id=18874880
shader_id=69
shader_id=512
shader_id=18876928
shader_id=2560
shader_id=27263045
shader_id=1361
shader_id=17059909
shader_id=94374400
shader_id=18874437
shader_id=84168773
shader_id=17062400
shader_id=27265536
shader_id=909
shader_id=17305729
shader_id=18875277
shader_id=52428869
shader_id=52431360
shader_id=27265647
shader_id=18092101
shader_id=127928832
shader_id=85983744
shader_id=52429312
shader_id=153092608
shader_id=153093005
shader_id=153092165
```

**Comment by DrUm78** [comment]
@fgsfdsfgs By any chance, have you got the opportunity to log those shaders? Or any idea how I could do it myself?

**Comment by fgsfdsfgs** [comment]
Should be fixed in da5b744.

**Comment by DrUm78** [comment]
Fixed. Thank you for your reactivity as usual. 🙏
![IMG_0204](https://user-images.githubusercontent.com/46139740/235379165-691c218f-4f49-43c2-96e9-9fb307cc6a98.PNG)

**Comment by bhosle** [comment]
Can this fix be ported over to the ps2 version?
I modified [line 177](https://github.com/fgsfdsfgs/sm64-port/blob/c1dcd832b7650443339840ad3559ade756472396/src/pc/gfx/gfx_ps2_rapi.c#L177) in src/pc/gfx/gfx_ps2_rapi.c to mimic the change in da5b744 but the issue still remains on ps2 (real hardware)
